name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Python ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        include:
          - {version: '3.11', os: ubuntu-latest}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: ci_env.yml
          activate-environment: ci-env
          miniforge-version: latest
          python-version: ${{ matrix.version }}
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Install pip dependencies
        run: |
          pip install pyscf
      - name: Run tests
        run: |
          python -m pytest respondo --cov=respondo
      - name: Run examples
        run : |
          pip install . -v
          cd examples
          python alpha_complex.py
          python alpha_example.py

  formatting:
    name: Code style
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: true
            environment-file: ci_env.yml
            activate-environment: ci-env
            miniforge-version: latest
            python-version: 3.11
      - name: Conda Info
        run: |
          conda info
          conda list
      - name: Run ruff and isort
        run: |
          ruff check respondo
          isort -rc respondo
